"""Add social links columns to Profile

Revision ID: fae676733883
Revises: 9fb0f57dd644
Create Date: 2025-03-08 01:50:55.584023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae676733883'
down_revision = '9fb0f57dd644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('behance', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('personal_website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vk', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('vk')
        batch_op.drop_column('telegram')
        batch_op.drop_column('personal_website')
        batch_op.drop_column('youtube')
        batch_op.drop_column('behance')
        batch_op.drop_column('github')

    # ### end Alembic commands ###
